{ config, lib, pkgs, ... }: {
  homebrew = {
    casks = [
      "ableton-live-suite10"
      "amethyst"
      "backblaze"
      "brave-browser"
      "bettertouchtool"
      "cleanmymac3"
      "cycling74-max"
      "docker"
      "dropbox"
      "eul"
      "evernote"
      "fantastical"
      "fork"
      "gpg-suite"
      "gswitch"
      "iina"
      "intellij-idea"
      "istat-menus"
      "iterm2"
      "karabiner-elements"
      "keepingyouawake"
      "keybase"
      "lastpass"
      "lulu"
      "nordvpn"
      "ransomwhere"
      "signal"
      "slack"
      "syncthing"
      "timely"
      "transmission"
      "virtualbox"
      "visual-studio-code"
      "vlc"
      "zoom"
    ];
    masApps = { "Unsplash Wallpapers" = 1284863847; };
  };
}
